site_name: Open Banking Connector docs
repo_url: https://github.com/finlabsuk/open-banking-connector
edit_uri: ""
repo_name: Open Banking Connector
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.tabs
    - search.share
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes
plugins:
  - search:
       lang: en
       separator: '[\s\-\.]'
  - git-revision-date
  - render_swagger

extra_css:
  - stylesheets/style.css

nav:
  - Overview:
    - README.md
    - Bank Integration Matrix: bank-integration-matrix.md
  - Get started:
    - get-started/README.md
  - Configuration:
    - configuration/README.md
    - Database settings: configuration/database-settings.md
    - Software statement profiles settings: configuration/software-statement-profiles-settings.md
    - Transport certificate profiles settings: configuration/transport-certificate-profiles-settings.md
    - Signing certificate profiles settings: configuration/signing-certificate-profiles-settings.md
    - Configuration sources settings: configuration/configuration-sources-settings.md
  - APIs:
    - interface/README.md
    - Bank Configuration API:
      - interface/bank-configuration/README.md
      - Set up a bank: interface/bank-configuration/set-up-a-bank.md
      - OpenAPI spec: interface/bank-configuration/openapi.md
    - Account and Transaction API:
      - interface/account-and-transaction/README.md
      - OpenAPI spec: interface/account-and-transaction/openapi.md 
    - Payment Initiation API:
      - interface/payment-initiation/README.md
      - OpenAPI spec: interface/payment-initiation/openapi.md
    - Variable Recurring Payments API:
      - interface/variable-recurring-payments/README.md
      - OpenAPI spec: interface/variable-recurring-payments/openapi.md
    - Auth Contexts API:
      - interface/auth-contexts/README.md
      - OpenAPI spec: interface/auth-contexts/openapi.md 
  - Contributor info:
      - contributor-info/README.md
      - Documentation:
        - contributor-info/documentation/README.md
        - Update: contributor-info/documentation/update-documentation.md
        - Deploy: contributor-info/documentation/deploy-documentation.md
      - Dev Environment: 
        - Install OB UK root certificate: contributor-info/dev-environment/install-ob-root-cert.md
        - Use Microsoft's Secret Manager: contributor-info/dev-environment/use-secret-manager.md
