site_name: Open Banking Connector docs
repo_url: https://github.com/finlabsuk/open-banking-connector
repo_name: Open Banking Connector
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.share
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes
plugins:
  - search:
       lang: en
       separator: '[\s\-\.]'
  - git-revision-date-localized:
      type: iso_date
  - render_swagger
extra_css:
  - stylesheets/style.css
copyright: Copyright &copy; 2023 Finnovation Labs Limited and contributors
nav:
  - Overview: README.md
  - Guide:
    - guide/README.md
  - Get started:
    - get-started/README.md
    - Set up configuration and secrets: get-started\set-up-configuration-and-secrets\README.md
    - Run Docker image: get-started\run-docker-image\README.md
    - Create bank registration: get-started\create-bank-registration\README.md
    - Create and authorise account access consent: get-started\create-and-authorise-account-access-consent\README.md
    - Get account data: get-started\get-account-data\README.md
  - Bank Integrations: bank-integrations.md
  - Configuration:
    - configuration/README.md
    - Database settings: configuration/database-settings.md
    - Software statement profiles settings: configuration/software-statement-profiles-settings.md
    - Transport certificate profiles settings: configuration/transport-certificate-profiles-settings.md
    - Signing certificate profiles settings: configuration/signing-certificate-profiles-settings.md
    - Encryption keys settings: configuration/encryption-keys-settings.md
    - Configuration sources settings: configuration/configuration-sources-settings.md
    - Open Telemetry settings: configuration/open-telemetry-settings.md
  - APIs:
    - apis/README.md
    - Bank Configuration API:
      - apis/bank-configuration/README.md
      - OpenAPI spec: apis/bank-configuration/openapi.md
    - Account and Transaction API:
      - apis/account-and-transaction/README.md
      - OpenAPI spec: apis/account-and-transaction/openapi.md 
    - Payment Initiation API:
      - apis/payment-initiation/README.md
      - OpenAPI spec: apis/payment-initiation/openapi.md
    - Variable Recurring Payments API:
      - apis/variable-recurring-payments/README.md
      - OpenAPI spec: apis/variable-recurring-payments/openapi.md
    - Auth Contexts API:
      - apis/auth-contexts/README.md
      - OpenAPI spec: apis/auth-contexts/openapi.md 
  - Contributor info:
      - contributor-info/README.md
      - Documentation:
        - contributor-info/documentation/README.md
        - Update: contributor-info/documentation/update-documentation.md
        - Deploy: contributor-info/documentation/deploy-documentation.md
      - Dev Environment: 
        - Install OB UK root certificate: contributor-info/dev-environment/install-ob-root-cert.md
        - Use Microsoft's Secret Manager: contributor-info/dev-environment/use-secret-manager.md
